In [68]:
import pandas as pd 
import numpy as np 
from scipy.stats import binomtest
from scipy.stats import wilcoxon
from scipy.stats import mannwhitneyu

In [2]:
df = pd.DataFrame({'Before':[1,3,5,7,8,763,256,753],'After':[7,13,9,8,40,267,536,548]})

In [3]:
df

   Before  After
0       1      7
1       3     13
2       5      9
3       7      8
4       8     40
5     763    267
6     256    536
7     753    548

# Sign Rank Test

In [5]:
df['difference'] = df['After'] - df['Before']

In [6]:
df

   Before  After  difference
0       1      7           6
1       3     13          10
2       5      9           4
3       7      8           1
4       8     40          32
5     763    267        -496
6     256    536         280
7     753    548        -205

Ho: Median difference=0

H1: Median difference!= 0

In [8]:
Postive = (df['difference'] > 0 ).sum()
Negative  = (df['difference'] < 0).sum()

print (f'Postive: {Postive}')
print(f'Negative: {Negative}')

Postive: 6
Negative: 2

In [9]:
n= Postive + Negative
n

8

In [10]:
Results = binomtest(k=Postive,n=n,p=0.5,alternative='two-sided')
print(Results)

BinomTestResult(k=6, n=8, alternative='two-sided', statistic=0.75, pvalue=0.2890625)

In [11]:
Results.pvalue

0.2890625

### conclusion 
Considering that the Pvalue > 0.05 we fail to reject the null hypothesis stating that the Median difference=0

In [13]:


def sign_rank_test(Data = df,After=df['After'],Before= df['Before']) :
    df['difference'] = After - Before 
    
    Postive = (df['difference'] > 0 ).sum()
    Negative  = (df['difference'] < 0).sum()
    
    Results = binomtest(k=Postive,n=n,p=0.5,alternative='two-sided')
    print('Ho: Median difference=0 \n H1: Median difference!= 0')

    if Results.pvalue > 0.05 :
        print('Considering that the Pvalue > 0.05 we fail to reject the null hypothesis stating that the Median difference=0')
    else : print('Considering that the Pvalue < 0.05 we  reject the null hypothesis stating that the Median difference!= 0')

In [14]:
sign_rank_test(df)

Ho: Median difference=0
 H1: Median difference!= 0
Considering that the Pvalue > 0.05 we fail to reject the null hypothesis stating that the Median difference=0

### Notes to improve the function: 
- Add the docstring 
- df['After'] = abstract it to column 1 and column 2 
- binom test parametrer input

# Wilcoxon signed-rank test

In [35]:
Stats,pvalue = wilcoxon(df['Before'],df['After'])

In [37]:
Stats

14.0

In [39]:
pvalue

0.640625

In [52]:
result = wilcoxon(df['Before'],df['After'])
result.pvalue

In [64]:
if result.pvalue > 0.05 :
    print('Considering that the Pvalue > 0.05 we fail to reject the null hypothesis stating that the Median difference=0')
else : print('Considering that the Pvalue < 0.05 we  reject the null hypothesis stating that the Median difference!= 0')

Considering that the Pvalue > 0.05 we fail to reject the null hypothesis stating that the Median difference=0

# Man whittney U test

In [79]:
df1 = pd.DataFrame({'Group1':[13,38,53,76,88,763,256,753],'Group2':[17,13,79,198,40,287,976,838]})

In [77]:
df1

   Group1  Group2
0      13      17
1      38      13
2      53      79
3      76      98
4      88      40
5     763     287
6     256     576
7     753     538

In [83]:
stats, pvalue = mannwhitneyu(df1['Group1'],df1['Group2'],alternative='two-sided')

In [85]:
stats

29.5

In [87]:
pvalue

0.8335142129533152